package com.example.chatapp.common

object FirebaseAuthErrorCodes {
    const val ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
    const val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"
    const val ERROR_USER_MISMATCH = "ERROR_USER_MISMATCH"
    const val ERROR_REQUIRES_RECENT_LOGIN = "ERROR_REQUIRES_RECENT_LOGIN"
    const val ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL = "ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL"
    const val ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE"
    const val ERROR_CREDENTIAL_ALREADY_IN_USE = "ERROR_CREDENTIAL_ALREADY_IN_USE"
    const val ERROR_USER_DISABLED = "ERROR_USER_DISABLED"
    const val ERROR_USER_TOKEN_EXPIRED = "ERROR_USER_TOKEN_EXPIRED"
    const val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
    const val ERROR_INVALID_USER_TOKEN = "ERROR_INVALID_USER_TOKEN"
    const val ERROR_OPERATION_NOT_ALLOWED = "ERROR_OPERATION_NOT_ALLOWED"
    const val ERROR_WEAK_PASSWORD = "ERROR_WEAK_PASSWORD"
    const val ERROR_TOO_MANY_REQUESTS = "ERROR_TOO_MANY_REQUESTS"
    const val ERROR_INVALID_CREDENTIAL = "ERROR_INVALID_CREDENTIAL"
    const val ERROR_INVALID_CUSTOM_TOKEN = "ERROR_INVALID_CUSTOM_TOKEN"
    const val ERROR_CUSTOM_TOKEN_MISMATCH = "ERROR_CUSTOM_TOKEN_MISMATCH"
    const val ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD"
    const val ERROR_INVALID_VERIFICATION_CODE = "ERROR_INVALID_VERIFICATION_CODE"
    const val ERROR_INVALID_VERIFICATION_ID = "ERROR_INVALID_VERIFICATION_ID"
}